### ISSUE TITLE
IS it can upload to apple store?

### ISSUE THREAD

**Issue by ilyi1116** [tciuro/NoticeView#10]
Hi,

this is very cool project,
i like it very very much~

and i use it in my new app..

i have an question... is it can upload to the apple store and no reject?

very very thank you ^^

**Comment by tciuro** [comment]
@ilyi1116, I cannot speak for Apple, but I don't see a reason why it would be rejected due to NoticeView. It could be rejected for a lot of reasons, but I don't think that NoticeView will be one of them.

For example, the app 'Piik' uses NoticeView and is available in the app store: http://www.piik.me.

**Comment by ilyi1116** [comment]
hi, tciuro

Thank you for your reply~

Eric
