### ISSUE TITLE
Neat

### ISSUE THREAD

**Issue by IAbuElRuzz** [tciuro/NoticeView#2]
I was taking a look at the NoticeView Project, it's really neat and useful!

Can i include it in my next project? 
I will link you in the credits if you like!

I am trying to include it over a MapView, but as you stated here :
"If you pass nil instead of a valid UIView, an NSInvalidArgumentException exception will be raised."

Obviously a mapView inside a ViewController is not a valid UIView, i will have to add an overlay as a view over the map view, and add NoticeView to the overlay.

**Comment by tciuro** [comment]
Thanks! :-)

You can do _whatever you want_. No restrictions whatsoever. Mentioning me in the credits would be great ;-)

Question: why can't you specify self.view in the ViewController? Is this because you're calling NoticeView from inside the MapView? If so, you could do this perhaps:

1) Subclass UIMapView
2) Add a public property, such as @property (nonatomic, assign) UIViewController *parentController;
3) @synthesize parentController;
4) When you're ready to display the NoticeView, use self.parentController.view;

If I understand correctly what you want to do, this should work. Let me know!

**Comment by IAbuElRuzz** [comment]
Excellent! 
That's what i needed to do exactly.
Thank you!! 
Good day

**Comment by tciuro** [comment]
Cool ;-)
